### ISSUE TITLE
Logos and Designs

### ISSUE THREAD

**Issue by franqq** [bespokeinteractive/afya-ehms-website#1]
@kgathuru Have a look at the EHMS Draft Website which is also available at http://www.afya-ehms.org/. I would like to hear what you think about this. Also please provide the designs - logos and favicon.

**Comment by ndisha** [comment]
@kgathuru sorry we ambushed you on this. We thought since you have already have the Afya EHMS logos done, you could share those with us or even better do your edits on this repo and we would do a git pull to get the website updated. Please let us know your thoughts.

**Comment by kgathuru** [comment]
Added some logos, an Afya mockup for the landing page, and favicons. I'll contribute what I can but I can't make any promises, I've been assigned to another project.

**Comment by ndisha** [comment]
Thank you so much @kgathuru; we will keep adding content including the beautiful images you have shared.
